# Generated by Django 5.1 on 2024-08-12 01:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0013_alter_feedback_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "teacher_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.RegexValidator(
                                message="Enter a valid name with alphabets and spaces only",
                                regex="^[A-Za-z ]+$",
                            ),
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit phone number",
                                regex="^[0-9]{10}$",
                            ),
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("commerce", "Commerce"),
                            ("humanities", "Humanities"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hire_date", models.DateField()),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="teachers/images/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
